# Generated by Django 5.1.5 on 2025-01-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_related_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="Время выполнения"),
        ),
    ]
