# Generated by Django 5.1.5 on 2025-01-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={},
        ),
    ]
