# Generated by Django 5.1.5 on 2025-01-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
    ]
